### ISSUE TITLE
Directly modifying layer properties on layer backed views

### ISSUE THREAD

**Issue by ppeszko** [erica/Auto-Layout-Demystified#10]
Hi Ericka,

I have a question regarding this code: 
https://github.com/erica/Auto-Layout-Demystified/blob/2cf725ade54cb7a88092e6bdbf74564979bbc265/2ndEdition/C07/05%20-%20Hybrid%20Scrollview/Constraints%20Pack/Nametag%20Utilities/View/NSView%2BBackgroundColor.m#L23

I thought you should not change directly layer properties unless you are doing it in `updateLayer` method. But perhaps I'm missing something. Can you please clarify it to me?

Thank you in advance :)
--
Patryk

**Comment by erica** [comment]
To the best of my knowledge this is not a problem. See https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreAnimation_guide/CreatingBasicAnimations/CreatingBasicAnimations.html <https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreAnimation_guide/CreatingBasicAnimations/CreatingBasicAnimations.html>

-- E

**Comment by ppeszko** [comment]
Wow, haven't expected such a fast reply :) thank you.

Regarding your link: this is exactly what confuses me. They give us this example and then writing here:
https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/index.html#//apple_ref/occ/instp/NSView/wantsLayer

"If the wantsUpdateLayer method returns NO, you should not interact with the underlying layer object directly. Instead, use the methods of this class to make any changes to the view and its layer. If wantsUpdateLayer returns YES, it is acceptable (and appropriate) to modify the layer in the view’s updateLayer method."

**Comment by ppeszko** [comment]
The question is, can I safely do it as well in other places or not? :)

**Comment by erica** [comment]
To the best of my understanding, yes. Otherwise a lot of my core animation stuff and layer styling wouldn't work.

-- E

**Comment by ppeszko** [comment]
Thank you!
